package com.littlebank.finance.domain.notification.domain;

public enum NotificationType {
    FEED_COMMENT, FEED_LIKE, COMMENT_REPLY, COMMENT_LIKE,
    CHALLENGE_JOIN, GOAL_PROPOSAL, GOAL_ACHIEVEMENT, MISSION_PROPOSAL, MISSION_ACCEPT, CHALLENGE_ACCEPT, GOAL_ACCEPT, GOAL_STAMP, MISSION_ACHIEVEMENT, CHALLENGE_ACHIEVEMENT, ADD_FRIEND, ADD_FAMILY, ACCEPT_FAMILY, MISSION_PROPROSAL
}
